apiVersion: apps/v1
kind: Deployment
metadata:
  name: theclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theclient-pod
  template:
    metadata:
      labels:
        app: theclient-pod
    spec:
      containers:
        - env:
            - name: FootballUri
              value: "http://theapi-service:7347/"
          image: squigs/annoyingclient:1.0
          name: theclient-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
