apiVersion: apps/v1
kind: Deployment
metadata:
  name: thegateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thegateway-pod
  template:
    metadata:
      labels:
        app: thegateway-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: squigs/annoyinggateway:1.0
          name: thegateway-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
