apiVersion: v1
kind: Service
metadata:
  name: thedb-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      #nodePort: 30000
  selector:
    app: thedb-pod
  type: LoadBalancer
