apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s_ocelot
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: theapi
  name: theapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: theapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s_ocelot
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: theapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
          image: squigs/annoyingapi:1.0
          name: theapi
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
