apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s_ocelot
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: thedb
  name: thedb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thedb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s_ocelot
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: thedb
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: marcus
          image: postgres:alpine
          name: thedb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: playerdata
      restartPolicy: Always
      volumes:
        - name: playerdata
          persistentVolumeClaim:
            claimName: playerdata
status: {}
