version: '3.4'

services:
  thedb:
    image: postgres:alpine # mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - playerdata:/var/lib/postgresql
  theapi:
    image: squigs/annoyingapi:1.0
    container_name: theapi
    build:
      context: annoying.api
      #target: debug
    environment:
      "DBServer": "thedb"
      "DBPort": "5432"
      "DBDatabase": "FootballDb"
      "DBUser": "marcus"
      "DBPassword": "password"
    ports:
      - 6515:80
    depends_on:
      - thedb

  theclient:
    image: squigs/annoyingclient:1.0
    container_name: theclient
    build:
      context: annoying.client
      #target: debug
    environment:
      "FootballUri": "http://theapi"
    ports:
      - 6510:80
    depends_on:
      - theapi

volumes:
  playerdata:
    external: true
